### ISSUE TITLE
代码参数未定义？

### ISSUE THREAD

**Issue by junck364** [BIT-wangzb/Cam_IMU_Calib_for_Vehicles#1]
您好：
修改CMakeLists.txt文件，cmake编译成功后，make -j提示异常：
solveQyx.cpp：115行
Eigen::Matrix3d Rc_g = Ric_test.inverse() * q2 * Ric_test;
代码中Ric_test未定义

是否可以提供完整代码和测试数据，非常感谢~！

**Comment by BIT-Octopus** [comment]
编译时遇到问题+1 
另外请问可否提供下代码的具体使用流程与数据格式的具体要求，感谢！
（好像发现了一个学校的？）

**Comment by Tausc** [comment]
将Ric_test相关的几行注释掉就可以了
